### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by toyflish** [spree-contrib/spree_globalize#15]
I was missing some translations I had to add by hand. They don't belong to i18n, maybe they should be in the repo? 

```
de:
  spree:
    i18n:
      translations: Übersetzungen
      store_translations: Store Übersetzungen
```

**Comment by tvdeyen** [comment]
Yes. I think they should be in this gem. Could you send us a pull request? That would be great. Thanks.

**Comment by tvdeyen** [comment]
I guess they are still in the `spree_i18n` gem. Right @alepore ?

**Comment by alepore** [comment]
yeah, we should probably move all the `i18n.*` keys here, maybe renaming them to `globalize:` ?

**Comment by alepore** [comment]
uhm, some keys are used both on i18n and globalize...

**Comment by tvdeyen** [comment]
I would say copy them over. Spree translation keys are too generic in most cases anyway. And it doesn't hurt to have some of them duplicated. 

What keys are we talking about?

**Comment by alepore** [comment]
https://github.com/spree/spree/blob/master/core/config/locales/en.yml#L721 (yes, english is in the core.....)

**Comment by alepore** [comment]
```
choose_language
this_file_language
localization_settings
available_locales
locales_displayed_on_frontend_select_box
language
```
are on i18n

**Comment by alepore** [comment]
I'd copy only the keys that are only here... or just leave them on i18n, they are just 4-5 keys.

**Comment by alepore** [comment]
to sum up, a nice work would be to move these on this gem, and change the namespacing to `globalize`

```yaml
en:
  spree:
    globalize:
      fields:
      locales_displayed_on_translation_forms:
      only_complete:
      only_incomplete:
      select_locale: 
      show_only: 
      supported_locales:
      translations:
```
